clojure-emacs/inf-clojure

- inf-clojure.el
Remove #_=> subprompts from the output
resolves #7
> Remove subprompts

- inf-clojure.el
It was never matching on the "default" branch with symbols, we switch to
strings.
---
I break it, I fix it :smile:
> Fix a problem with pattern matching on inf-clojure-repl-type

- inf-clojure.el
> Add lumo arglists

- inf-clojure.el
> Split inf-clojure-load-form by repl type

- inf-clojure.el
> Use inf-clojure--sanitize-command everywhere

- inf-clojure.el
A little fix for a forgotten friend.
Thanks!
> Fix missing inf-clojure-set-ns-form-lumo

- inf-clojure.el
> Lumo new stuff2

- inf-clojure.el
> Fix typo in docstring

- README.md
- inf-clojure.el
A lot of muscle memory thanks to cider for this.
> Bind C-c M-c to inf-clojure-connect

- inf-clojure.el
Change the way the response is calculated, not by `search-forward` the buffer used for redirection but by parsing the raw response. Taking into consideration the optional regexps, a list is calculated with beginning, end and prompt position (the logic is now in inf-clojure--string-boundaries, which can be unit tested).
This implicitly solves a hidden bug in inf-clojure--process-response, which was not able to identify the prompt in some cases because of the many search-forward.
Finally, this new information is logged so that bugs can be detected more easily.
> Calculate response boundaries explicitly

- inf-clojure.el
Improves the code so that empty strings are not sent to the process anymore. It also avoids trimming \t because they are actually used by some REPL.
> Protect against empty commands

- README.md
Onstead of being buried in the source, I added it to the README.
> Add Multiple Process Support section to README

- inf-clojure.el
> Add planck-specific function for show-arglist, fixes #105

- inf-clojure.el
> Add :safe clause for inf-clojure-repl-use-same-window

- CHANGELOG.md
- README.md
- inf-clojure.el
The new inf-clojure-tools-deps-cmd will be used when the deps.edn file is going
to be detected in the project root.
> Introduce the tools.deps project type

- CHANGELOG.md
- inf-clojure.el
> [Fix #113] Send REPL string always, even if empty

- README.md
Citing cljs-tooling for enabling support.
> Add README note about ClojureScript REPL support

- inf-clojure.el
I went through a checkdoc session and fixed what was easiest to fix.  Not
everything, but it is a good start.
> Fix and reword docstring

- inf-clojure.el
Fixes https://github.com/clojure-emacs/inf-clojure/issues/141
> Require seq library.

- inf-clojure.el
Fix https://github.com/clojure-emacs/inf-clojure/issues/134
> set inf-clojure-tools-deps-cmd to "clojure"

- README.md
> Explain how to create and connect to a socket REPL in README.

- README.md
A few updates to links and formatting in the README
Thanks!
> A few updates to links and formatting in README

- inf-clojure.el
- test/inf-clojure-tests.el
looks like this got copy pasted from some emacs lisp files which were part of emacs
> Mark this is not part of emacs. probably copy paste error

- inf-clojure.el
**Replace this placeholder text with a summary of the changes in your PR.
The more detailed you are, the better.**
Thanks!
> Remove a noise character

- inf-clojure.el
**Replace this placeholder text with a summary of the changes in your PR.
The more detailed you are, the better.**
Thanks!
> Put a space after prompt
