clojure-emacs/inf-clojure

- README.md
in Windows OS, the repl is not responsive. for example, typing `(+ 1 1)` and `ENTER` does not return anything. The cursor just drops to new line.
I found the solution here https://groups.google.com/forum/#!topic/leiningen/48M-xvcI2Ng.
Basically, just create file `.jline.rc` and put this line on this file.
`jline.terminal=unsupported`
I don't know where to put it. So, I decided just to add Troubleshooting section in README.md
> Solution to unresponsive repl in Windows OS

- inf-clojure.el
I tried to use `C-c C-a` as the inf-clojure-show-arglist command, then I couldn't see any output.
I'm not sure, but maybe this command needed new-line mark after that command.
Thanks.
> Add new-line mark after inf-clojure-arglist-command

- inf-clojure.el
Modify `inf-clojure-eval-region` as follows:
- if region already ends with one or more newlines replace it with a single newline
- if region doesn't end with a newline then add one
resolves #18
> Too many newlines

- inf-clojure.el
- Pass and-go parameter to inf-clojure-eval-region
- Use point-min and point-max instead of beginning-of-buffer and end-of-buffer
> Refactoring

- README.md
- inf-clojure.el
This probably needs some cleaning up and maybe some changes.
Would be really nice if you could take a look.
I started out with the code from cider and changed things where needed. Haven't hit any performance issues so far. Eldoc works in clojure buffer and repl.
> add eldoc support

- inf-clojure.el
Because 'if-let' is defined only on development Emacs(version 25).
> Fix for older Emacs

- inf-clojure.el
Planck, https://github.com/mfikes/planck, the Clojurscript
repl on OSX, uses somewhat different commands to achieve
things like set-ns, apropos, dir etc. This commit
lets the user customize these commands.
> Add possibility to customize more vars

- README.md
- inf-clojure.el
Coming takes a cons pair for connecting to tcp connections. This allows `inf-clojure` (or setting `inf-clojure-program`) to accept a cons pair for connecting to a clojure socket repl server. I tested this with planck via `planck -n 5555`.
> Accept cons pair for tcp connections.

- inf-clojure.el
When navigating to previous input history and *current input is empty*,
the `backward-sexp' call in function `inf-clojure-get-old-input' would
not respect comint prompt boundary and jump to beginning of line. This
caused the prompt text to be stored in `comint-stored-incomplete-input',
which is annoying and causes even more problems if prompt text is set to
read-only.
This change makes sure that the extracted buffer substring for current
input does not include the prompt, even when input is empty or just
white space.
Also, introduce a regexp to use for `comint-prompt-regexp' which matches
both main prompt and sub prompts, so that boundary is respected when
`comint-use-prompt-regexp' is set to t.
Fixes #35
> Fix prompt being included in input history

- CHANGELOG.md
- inf-clojure.el
The patch allow the user to disable the request "Set ns: ..." on C-c
M-n. The default is to always prompt.
(No need?) -> You've updated the readme (if adding/changing user-visible functionality)
> Add defcustom `inf-clojure-prompt-when-set-ns`

- inf-clojure.el
This patch adds the `inf-clojure-repl-flavor` defcustom in order to
support different kind of configurations based on the selected flavor.
The default flavor is `'clojure`, and the other supported one is `'lumo`.
It also adds defcustoms to further customize hostname, port and
classpath used in the Lumo flavor.
--
The defcustoms for the following are already ok:
* `inf-clojure-set-ns-form`
* `inf-clojure-macroexpand-form`
* `inf-clojure-macroexpand-1-form`
TODOs
* `(setq inf-clojure-var-source-form "(lumo.repl/source %s)")` - https://github.com/anmonteiro/lumo/issues/84
* `(setq inf-clojure-ns-vars-form "(lumo.repl/dir %s)")` - https://github.com/anmonteiro/lumo/issues/87
* `(setq inf-clojure-var-apropos-form "(lumo.repl/apropos %s)")` - https://github.com/anmonteiro/lumo/issues/86
* …
> Support REPL flavors and Lumo

- CHANGELOG.md
- inf-clojure.el
This patch renames all the inf-clojure-*-command defcustoms to
inf-clojure-*-form where the content is a Clojure form to be evaluated
at the REPL.
> Rename to -form where appropriate

- CHANGELOG.md
- README.md
> Modify CHANGELOG and README for REPL types

- CHANGELOG.md
- README.md
- inf-clojure.el
The patch introduces a way to globally disable prompting. It deletes
`inf-clojure-prompt-when-set-ns`.
> Add inf-clojure-prompt-on-commands and closes #48

- inf-clojure.el
Now every function calls the more reliable inf-clojure-symbol-at-point.
Please let me know if there was some valid reason not to do so, but it was not behaving really well, especially in conjunction with all these filters we have in place.
> Kill inf-clojure-var-at-point

- inf-clojure.el
This patch adds `inf-clojure-ns-vars-form-lumo` and a function that
return the correct `inf-clojure-ns-vars-form` variant given the REPL
type.
> Add dir support in Lumo

- inf-clojure.el
I opened this PR basically to raise a flag around synchronicity and asking for what is the best way to solve them. It is a very sporadic problem I get when I try to detect the REPL type while waiting for a REPL detection that finishes. As you can imagine these things are difficult to reproduce and I'd like to ask folks to try `inf-clojure` without this patch in `lumo` and report what happens.
I found http://blog.jorgenschaefer.de/2014/05/race-conditions-in-emacs-process-filter.html and put a lock in there, which is a hack.
Thanks!
> Fix repl type sync

- README.md
- inf-clojure.el
This patch supports lumo -d (dumb terminal) and suggests in the README a
command to launch it this way.
> Officially support lumo -d (dumb terminal) only

- inf-clojure.el
A fix was necessary for a regression caused by the fact that now
`inf-clojure--send-string` adds a newline at the end of the string it
sends to the process.
> Fix newline append on eval functions

- CHANGELOG.md
- README.md
- inf-clojure.el
Added support for the Planck REPL
Thanks!
> Fix #56 Add special handling for Planck REPLS

- inf-clojure.el
> Fix three "variable is void" bugs

- CHANGELOG.md
- README.md
- inf-clojure.el
Add new interactive command to connect to a socket-repl
Thanks!
> [Fix #58] Add function to connect to remote repl

- CHANGELOG.md
- inf-clojure.el
I will need to fix the arglists function as well, it does not work properly for edge cases, I already have some code ready, but I figured I should do another PR.
Also, the same approach should be used for completions, but completions require more work that is why I avoided putting it here.
Thanks!
> [Fix #63] Avoid spurious output by using buffer redirection

- inf-clojure.el
This modifies names for consistency and also handles the cases when an arglists cannot be found/computed (e.g.: you are on a symbol that has not be required).
> Ovarhaul arglists

- CHANGELOG.md
- inf-clojure.el
Reported on Slack by @adamfrey
Thanks!
> Fix a bug causing read to output for expression

- inf-clojure.el
lumo.repl/get-completions takes two arguments.
https://github.com/anmonteiro/lumo/blob/master/src/cljs/snapshot/lumo/repl.cljs#L1252
So I added map str function into the callback, now I'm getting completions suggestions from company-mode.
- [x ] The commits are consistent with our [contribution guidelines][1]
- [x ] The new code is not generating bytecode or `M-x checkdoc` warnings
Thanks!
> add callback argument to lumo get-completions

- CHANGELOG.md
- inf-clojure.el
> Fix for #83

- inf-clojure.el
It started to rightfully complaining of (atom) missing the initial value. Fixed.
> Fix completions in new lumo

- inf-clojure.el
Lumo has pretty print by default enabled. So this fix is necessary in order to avoid seeing newlines in eldoc.
> Disable pretty print when fetching lumo arglists

- CHANGELOG.md
- README.md
- inf-clojure.el
**Replace this placeholder text with a summary of the changes in your PR.
The more detailed you are, the better.**
Thanks!
> Fix for #79

- README.md
- inf-clojure.el
Log commands and responses from/to the Inf-Clojure process. It can be enabled with `(setq inf-clojure-log-activity t)`. Vital for debugging.
> Introduce inf-clojure-log-activity

- inf-clojure.el
Credit to @cgrand for this idea, which works way better and avoids the "No such namespace: js" error that we get when trying to detect a lumo/planck repl in a clj repl.
> Adopt find-ns for detecting the repl type

- CHANGELOG.md
- inf-clojure.el
Introduce double checking in the busy wait that detects if the inf-clojure process (the REPL) has completed and sent back everything. This removes the slowness that was triggered by having accept-process-output in the while body: we can take advantage now of its output to wait as well.
> Fix #89 and speed

- inf-clojure.el
> Trim the string before checking nil

- README.md
> Rephrase process logging description a bit

- CHANGELOG.md
- inf-clojure.el
> [Fix #96] Use inf-clojure--send-string instead of comint-proc-query

- inf-clojure.el
For now only one thing has been done:
* Split the only when-let for backward compatibility
Did not update the CHANGELOG in order to wait if this is the only thing to do.
> Be compatible with older Emacs

- inf-clojure.el
Go over all the defcustom so that we set the correct `:safe` or `risky`
property.
Fix for #98.
Debatable and open for discussion:
The `inf-clojure-*-cmd`s will be considered risky if the value is a string (indicating a command line
execution) and safe is a cons cell containing a valid endpoint.
> [Fix #89] Set defcustom safety

- inf-clojure.el
- [x ] The commits are consistent with our [contribution guidelines][1]
- [x ] The new code is not generating bytecode or `M-x checkdoc` warnings
- Move defcustoms to before first referenced
- Change `(save-excursion (set-buffer ...)..)` to `(with-current-buffer ...)`
> Remove compile warnings, fixes #75

- inf-clojure.el
To not get weird completions the expression boundries cant contain open or close parenthesis and open or close brackets. Otherwise, in the case of lumo, the completions will look like the following picture.
https://user-images.githubusercontent.com/6074754/27034766-3de33bbe-4f7f-11e7-821f-62204cd9f02d.png
So far after adding these chars I've not experienced this again.
- [x ] The commits are consistent with our [contribution guidelines][1]
- [x ] The new code is not generating bytecode or `M-x checkdoc` warnings
Thanks!
> add expression break chars

- inf-clojure.el
In the work I did with #105, I missed a closing paren, which caused inf-clojure with Planck to misbehave.
- [√ ] The commits are consistent with our [contribution guidelines][1]
- [√ ] The new code is not generating bytecode or `M-x checkdoc` warnings
> Fix bug introduced by #105

- CHANGELOG.md
- README.md
- inf-clojure.el
This patch adds a defcustom, inf-clojure-skip-project-detection, that when
non-nil skips the project detection so that only inf-clojure-generic-cmd will
be used.  This is very useful for projects that don't have standard layouts.
> Introduce inf-clojure-project-type defcustom

- CHANGELOG.md
- inf-clojure.el
Now the code sets the `inf-clojure-repl-type` buffer local var in the `inf-clojure-buffer` when a REPL type is detected. This solves the weird errors that were happening when working within the REPL buffer because `inf-clojure-repl-type` is nil.
>  [Fix #116] Set inf-clojure-buffer REPL type on detect

- CHANGELOG.md
- README.md
- inf-clojure.el
Now the user can provide a custom parsing function for completion and therefore
has complete (pun intended) freedom in what to use for it. Some could use
compliment completion for instance or even use directly what cider provides.
The defcustom defaults to inf-clojure-list-completions, which can only parse
candidates coming as a Lisp list of strings.
Thanks!
> Introduce inf-clojure-completions-fn defcustom

- CHANGELOG.md
- inf-clojure.el
The functionality was erroring out cause of wrong function signature.
Moreover the key binding was not working because `C-A` is interpreted as `C-a` by
emacs (it seems, seeking Elisp expert advice).
This patch also add `C-c C-S-A` to `inf-clojure-mode` (the REPL itself).
Thanks!
> Fix inf-clojure-apropos

- CHANGELOG.md
- inf-clojure.el
This patch introduces reduces `inf-clojure-proc`'s responsabilities to only one:
return the processs. The new `inf-clojure--proc-or-error` will do both returning
and erroring.
This is necessary because while it is good to communicate an error on "eval"
operations, it is not good to have it on "under the hood" and very frequent
ones like completion and get arglists.
Thanks!
> Avoid throwing an error for frequent operations like completion

- CHANGELOG.md
- inf-clojure.el
> Add macroexpand forms for Lumo

- CHANGELOG.md
- inf-clojure.el
A couple of changes to the way the redirect buffer and the main REPL buffer are
created was needed in order to have actual loading of .dir-locals.el.
Additionally, code in inf-clojure--process-response has been simplified and
corrected.
Thanks!
> Support loading directory locals in our buffers

- .gitignore
- .travis.yml
- CHANGELOG.md
- Cask
- inf-clojure.el
- test/inf-clojure-tests.el
It was missing, but it is actually used for identifying completions bounds.
> Improve the completion bounds detection (now with keywords)

- CHANGELOG.md
- README.md
- inf-clojure.el
It will evaluate (require 'ns :reload) or (require 'ns :reload-all) at the
REPL, depending on the arguments passed in.
- `C-u M-x inf-clojure-reload`: prompts for a namespace name.
- `M-- M-x inf-clojure-reload`: executes (require ... :reload-all).
- `M-- C-u M-x inf-clojure-reload`: reloads all AND prompts."
This works only from source buffers at the moment (like all the other namespace commands).
Thanks!
> Introduce inf-clojure-reload

- CHANGELOG.md
- inf-clojure.el
- test/inf-clojure-tests.el
This patch improves the parsing and sanitation of command and make sure, with
tests, that we do things correctly.
Thanks!
> Improve command sanitation code

- inf-clojure.el
- test/inf-clojure-tests.el
The patch avoids removing newlines when comments are there and re-enables
sending empty commands (like in #120, how many times do I need to fix this?
:S).
Thanks!
> Sanitation should skip comments

- inf-clojure.el
This one is solving the weird duplicating prompt issue. After the sanitation
patch we were sending newline twice.  Using comint-send-string because it is
more low-level and does not modify the input string, which we are building
correctly already (hopefully).
See also https://github.com/clojure-emacs/inf-clojure/pull/138.
> Use comint-send-string

- inf-clojure.el
Marking all values which validate `functionp` as "safe" means that any file can potentially execute any arbitrary code on the Emacs instance it's been opened on.  This commit should remove this possibility.
PS: I don't use this package myself: I'm trying to semi-automatically detect all occurrences of this issue (`:safe 'functionp`) on all Melpa packages, so apologies for any mistakes!  
Thanks!   
Thanks!
> [security] Don't execute arbitrary functions

- inf-clojure.el
The feature was kind of broken, this patch makes sure it actually works.
> Remove quotes from reload and fix argument parsing

- inf-clojure.el
This seems to work for me. I have not seen any problems with inf-clojure, and I have been using it daily on two different systems. I believe it resolved the issue when using Racket/Geiser, but I have not tested it extensively.
> [Fix #154] Use setq-local for comint-input-sender

- CHANGELOG.md
- README.md
- inf-clojure.el
This patch introduces the defcustoms necessary for supporting joker.
> Support joker

- inf-clojure.el
Fixes a doc typo introduced in https://github.com/clojure-emacs/inf-clojure/pull/160
> Fix typo in inf-clojure--joker-repl-form

- CHANGELOG.md
- inf-clojure.el
When using the REPL, whenever you'd type the function name, because
`Throwable` is JVM specific, `eldoc-mode` would try to look up the
function and when it wouldn't find it, it would bomb out with the
complaint that `Throwable` wasn't defined. Which is to be expected since
it's not running on JVM.
Looking at the documentation
https://docs.oracle.com/javase/10/docs/api/java/lang/Throwable.html
> The Throwable class is the superclass of all errors and exceptions in the Java language.
And in C#, Exception
https://docs.microsoft.com/en-us/dotnet/api/system.exception?redirectedfrom=MSDN&view=netframework-4.8
> This class is the base class for all exceptions.
by checking the relevant …
> Fix for eldoc-mode for ClojureCLR

- CHANGELOG.md
- inf-clojure.el
Nice interaction to see the form and then the output.
I'm a big fan of the insert in the repl commands so adding them here.
- 14 errors before me. Will clean up in another pass
- doesn't seem like an obvious place to put this right now
Thanks!
> Insert commands

- CHANGELOG.md
- README.md
- inf-clojure.el
- todo.org
Set REPL type at startup from startup form. Defcustom to override or set if custom startup form is used and otherwise prompt user for repl type.
Thanks!
> Set REPL type from startup form, prompt, or defcustom at startup

- CHANGELOG.md
- inf-clojure.el
closes https://github.com/clojure-emacs/inf-clojure/issues/173
> Use clojure-mode project detection

- CHANGELOG.md
- inf-clojure.el
If there was no containing directory with a project file the
default-directory would be nil. This leads to problems in starting up
inf-clojure and also annoyingly seems to set an error in a timer:
> Error running timer 'auto-revert-buffers (wrong-type-argument string nil)
Fixes https://github.com/clojure-emacs/inf-clojure/issues/178
> [Fix #178] Ensure there is a directory for comint (thanks mcphailm)

- inf-clojure.el
When clearing comint buffer ensure we are actually in the repl buffer
> Ensure comint-truncate-buffer call is from the repl buffer

- inf-clojure.el
Correct misspelled function.
Fixes #181 
----
Thanks!
> Correct misspelled function. Fixes #181

- .circleci/config.yml
- Makefile
- inf-clojure.el
- test/inf-clojure-tests.el
This patch makes sure that we trim at the right of the sanitized command only.
I am open to get rid completely of the sanitation but I do not have the time
now for trying on all the platform.
- [] You've updated the changelog (if adding/changing user-visible functionality)
- [] You've updated the readme (if adding/changing user-visible functionality)
> [Fix #152]  Sanitize should only remove whitespace at the end of a command

- inf-clojure.el
- test/inf-clojure-tests.el
This sends the contents of the buffer. However, newlines cause the
prompt to be returned. You can see this with even a regular clojure
repl:
```bash
❯❯❯ clojure
Clojure 1.10.2
user=>
user=>
user=>
```
(note using `clj` has rlwrap which hides a bit of this so make sure to
use `clojure`).
But what we can do is make sure to transform
```clojure
(defn foo [] ...)
(defn bar [] ...)
```
into
```clojure
(defn foo [] ...)
(defn bar [] ...)
```
So that the newlines don't trigger more repl prompts. Real world usage below:
Before:
```clojure
parse=>
nil
parse=> parse=> nil
parse=> parse=> #'parse/data
parse=> parse=> #'parse/parse-where
parse=> parse=> #'parse/keywords
parse=> parse=> #'parse/tokenize
parse=>
parse=> #'parse/parse
parse=> parse=> #'parse/translate-where
parse=> parse=> nil
parse=> …
```
> Handle newlines between forms for `inf-clojure-eval-buffer`

- inf-clojure.el
Just a simple call to font lock the repl when inserting
> Font lock on repl inserts

- CHANGELOG.md
- README.md
- inf-clojure.el
Helpful little function to ease the use case of multiple connections. There's a global connection that all commands use: `inf-clojure-buffer`. Changing this allows using different connections. This function just sets that to current buffer if in a repl, shows a list of live process inf-clojure repls if not, and if given a prefix, always shows a list so you can switch even if you're currently in a repl. The repl type is in a defvar-local `inf-clojure-repl-type` so that doesn't need to be set or re-inferred.
Renaming buffers with projects and repl types makes this quite nice, and the dead simple way it works means that things can be evaluated from any buffer (project irrespective) and no edge cases like last focused buffer or anything like that.
> Function to select repls as the current active connection

- inf-clojure.el
Fix following warnings
- referencing free variables
- unused variables
- unspecified `:type` attribute
```
In inf-clojure-get-feature:
inf-clojure.el:168:27: Warning: reference to free variable
‘inf-clojure-repl-type’
In inf-clojure-proc:
inf-clojure.el:198:29: Warning: reference to free variable
‘inf-clojure-buffer’
In inf-clojure-set-repl:
inf-clojure.el:228:13: Warning: assignment to free variable
‘inf-clojure-buffer’
In inf-clojure--modeline-info:
inf-clojure.el:281:21: Warning: reference to free variable
‘inf-clojure-buffer’
inf-clojure.el:412:12: Warning: defcustom for ‘inf-clojure-custom-startup’
fails to specify type
inf-clojure.el:412:12: Warning: defcustom for ‘inf-clojure-custom-startup’
fails to specify type
In inf-clojure-reload-form:
inf-clojure.el:474:33: Warning: Unused …
```
> Fix byte compile warnings

- CHANGELOG.md
- README.md
- inf-clojure.el
Eldoc is quite nice and puts the function signatures in the
minibuffer. But it does this at a cost. Since inf-clojure only uses a
single connection (currently at least) the commands interrupt the
values of `*1`, `*2`, etc. Further, this can lead to multiple prompts
appearing in the repl buffer.
```clojure
user=> user=> (map inc (range 4))
(1 2 3 4)
user=> user=> *1
nil
user=>
```
`user` appears multiple times, and then `*1` has been bound to the
result of getting arglists
```clojure
user=> (+ 1 1)
2
user=> *1
([f] [f coll] [f c1 c2] [f c1 c2 c3] [f c1 c2 c3 & colls])
```
The multiple prompts is quite annoying when inserting forms into the
repl.
Note that `*1` is oftentimes `nil` because eldoc just runs `(try (:arglists (meta _whatever-your-cursor-is-on)) (catch nil))` whenever your cursor …
> Adds an option to disable eldoc

- inf-clojure.el
The following now works: (inf-clojure "clojure -Sdeps \"{:deps {insn/insn {:mvn/version \\\"0.5.4\\\"}}}\"")
Thanks!
> Improve cmd string splitting, fixes #185

- CHANGELOG.md
- inf-clojure.el
This addresses https://github.com/clojure-emacs/inf-clojure/issues/168 by creating `inf-clojure--recent-buffer` to keep track of the buffer the repl was switched to from.  It's set on both `inf-clojure` and `inf-clojure-switch-to-repl` which hopefully means it can never be unintentionally `nil`.  If `inf-clojure-switch-to-recent-buffer` is called and `inf-clojure--recent-buffer` IS `nil` the message `"inf-clojure: No recent buffer known."` is sent.
This only tracks the most recent buffer among all repls, it will not manage multiple references in the case of multiple repls.
I'm by no means an elisp expert, if there are improvements to be made I'm happy to hear them.  I'm gonna try to take on more changes, I love having an opportunity to contribute!
Before submitting the …
> Added function for switching back from an inf-clojure buffer

- CHANGELOG.md
- README.md
- inf-clojure.el
Added support for ClojureCLR repl via `lein-clr`. Updated README to reflect changes.
> Add ClojureCLR support

- CHANGELOG.md
- inf-clojure.el
When inserting forms into the repl, the buffer doesn't always scroll to
show the new input and result. This has been fixed in CIDER in a similar
way so bringing the same trick here.
https://github.com/clojure-emacs/cider/pull/2590
> Ensure repl scrolls on insert

- inf-clojure.el
Whilst playing with inf-clojure-mode-map, some previous binds are overriden, because copy-keymap is used instead of set-parent-map. This will help for that.
> Use comint-mode-map as parent map instead

- CHANGELOG.md
- inf-clojure.el
Displays a message after setting the repl.
When manually setting a repl with `inf-clojure-set-repl`, there is no visual indication that the repl has successfully been changed. This has confused me a few times in the past so I added a message.
This was [briefly discussed on slack](https://clojurians.slack.com/archives/C099W16KZ/p1672414905867309)
Thanks!
> Display message after setting repl

- CHANGELOG.md
- README.md
- inf-clojure.el
This PR addresses the issue #209 I raised yesterday, introducing the `inf-clojure-socket` function to create and connect to a socket REPL from within Emacs.
Additionally:
- There are two buffer variables `inf-clojure-buffer` as before and also `inf-clojure-cljs-buffer`. This is a somewhat dirty solution that builds on the current implementation, this is useful as it's common for projects to use clj & cljs together.
- `inf-clojure--get-buffer` returns the right global buffer variable `inf-clojure-buffer` or `inf-clojure-cljs-buffer` depending on whether your are currently in a clojurescript buffer/file.
- I've deliberately tried not to make all functions work with `inf-clojure-cljs-buffer` to avoid this PR ballooning, I've only done the neccessary changes to allow clojurescript-mode …
> Include user function to create a socket repl inside emacs/inf-clojure

- inf-clojure.el
Fixes: https://github.com/clojure-emacs/inf-clojure/issues/211
**How to use:**
To use one of the defaults defined in
`inf-clojure-socket-repl-startup-forms`, just `m-x inf-clojure-socket-repl` and choose your startup.
To add your own custom startup
```emacs-lisp
(setq inf-clojure-custom-startup
"clojure -J-Dclojure.server.repl=\"{:port %d :accept clojure.core.server/repl}\" -A:grepl")
```
This will prompt you for a repl type so it's useful to also include
```emacs-lisp
(setq inf-clojure-custom-repl-type 'clojure)
```
Or set these in a .dir-locals.el file for each project with
```emacs-lisp
;;; Directory Local Variables
;;; For more information see (info "(emacs) Directory Variables")
((nil . ((inf-clojure-custom-startup . "clojure -J-Dclojure.server.repl=\"{:port %d :accept …
```
> Cleanup socket repl startup.

- CHANGELOG.md
- inf-clojure.el
Context - Same as https://github.com/clojure-emacs/clojure-mode/pull/663
> Replace `beginning-of-defun` fn
